Tutorial URL: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

#  Deep Learning with PyTorch: A 60 Minute Blitz » What is PyTorch?

In [80]:
# preamble
import torch
import numpy as np

## 1. Creating Tensors

In [81]:
x = torch.empty(5,3)
print(x)

x = torch.rand(5,3)
print(x)

x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.8443,  0.0000]])
tensor([[ 0.9423,  0.3261,  0.1387],
        [ 0.0299,  0.1679,  0.5785],
        [ 0.2708,  0.7301,  0.2546],
        [ 0.8891,  0.2738,  0.9854],
        [ 0.0211,  0.7829,  0.3375]])
tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [82]:
x = torch.tensor([[5,4,3], [2,1,3]])
print(x)

x = x.new_ones(5,3) # new_* methods take in sizes
print(x)

x = x.new_ones(5,4, dtype=torch.float)
print(x)

x = torch.rand_like(x)
print(x)

x = torch.rand_like(x, dtype=torch.double)
print(x)

tensor([[ 5,  4,  3],
        [ 2,  1,  3]])
tensor([[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]])
tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])
tensor([[ 0.0647,  0.2321,  0.0656,  0.5289],
        [ 0.4121,  0.5446,  0.3185,  0.9184],
        [ 0.7062,  0.0166,  0.8022,  0.6583],
        [ 0.5018,  0.4282,  0.0181,  0.9692],
        [ 0.4918,  0.9432,  0.7793,  0.7541]])
tensor([[ 0.4776,  0.2803,  0.3562,  0.3191],
        [ 0.7131,  0.5154,  0.8778,  0.7412],
        [ 0.1402,  0.8723,  0.4108,  0.3885],
        [ 0.4872,  0.7408,  0.1075,  0.6395],
        [ 0.2368,  0.6319,  0.7364,  0.4456]], dtype=torch.float64)


In [83]:
print(type(x))
print(x.dtype)
print(x.shape)
print(x.size())
print(x.shape[1])

# torch.Size is in fact a tuple, so it supports all tuple operations.

<class 'torch.Tensor'>
torch.float64
torch.Size([5, 4])
torch.Size([5, 4])
4


## 2 Operations

In [84]:
y = torch.rand_like(x)
print(y)

tensor([[ 0.7188,  0.5968,  0.6259,  0.3194],
        [ 0.6302,  0.1865,  0.9464,  0.6626],
        [ 0.0088,  0.2570,  0.4421,  0.0703],
        [ 0.8153,  0.4359,  0.6574,  0.6764],
        [ 0.3436,  0.8716,  0.7304,  0.3576]], dtype=torch.float64)


In [85]:
z = x + y
print(z)

z = torch.add(x,y)
print(z)

z = x.new_zeros(x.size())
print(z)

torch.add(x,y, out=z)
print(z)

y.add_(x)
print(y)

tensor([[ 1.1964,  0.8771,  0.9822,  0.6385],
        [ 1.3432,  0.7019,  1.8241,  1.4038],
        [ 0.1490,  1.1293,  0.8530,  0.4588],
        [ 1.3024,  1.1767,  0.7650,  1.3159],
        [ 0.5804,  1.5035,  1.4667,  0.8033]], dtype=torch.float64)
tensor([[ 1.1964,  0.8771,  0.9822,  0.6385],
        [ 1.3432,  0.7019,  1.8241,  1.4038],
        [ 0.1490,  1.1293,  0.8530,  0.4588],
        [ 1.3024,  1.1767,  0.7650,  1.3159],
        [ 0.5804,  1.5035,  1.4667,  0.8033]], dtype=torch.float64)
tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]], dtype=torch.float64)
tensor([[ 1.1964,  0.8771,  0.9822,  0.6385],
        [ 1.3432,  0.7019,  1.8241,  1.4038],
        [ 0.1490,  1.1293,  0.8530,  0.4588],
        [ 1.3024,  1.1767,  0.7650,  1.3159],
        [ 0.5804,  1.5035,  1.4667,  0.8033]], dtype=torch.float64)
tensor([[ 1.1964,  0.8771,  0.9822,  0.6385],
        [ 1.3432,  0.7019,

In [86]:
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.

x = torch.rand(5,3)
print(x)

y = torch.zeros(5,3)
print(y)

x.t_()
print(x)

x.t_()
x.copy_(y)
print(x)

tensor([[ 0.2907,  0.5893,  0.9967],
        [ 0.4918,  0.1233,  0.4416],
        [ 0.3348,  0.7893,  0.1919],
        [ 0.5406,  0.1234,  0.9493],
        [ 0.6363,  0.2944,  0.2143]])
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])
tensor([[ 0.2907,  0.4918,  0.3348,  0.5406,  0.6363],
        [ 0.5893,  0.1233,  0.7893,  0.1234,  0.2944],
        [ 0.9967,  0.4416,  0.1919,  0.9493,  0.2143]])
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])


In [87]:
x = torch.tensor([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(x)
x[1:3, :2] # row 1 and 2, column 0 and 1

tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])


tensor([[  5,   6],
        [  9,  10]])

In [88]:
# Playing with resizing, attempting to convert 
x = torch.tensor([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(x.size())

a = x.view(4,-1) # expected 4,3 
print(a)
print(a.size())

b = x.view(6,2)
print(b)
print(b.size())

c = x.view(12,1)
print(c)
print(c.size())

d = x.view(12)
print(d)
print(d.size())

torch.Size([3, 4])
tensor([[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [ 10,  11,  12]])
torch.Size([4, 3])
tensor([[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10],
        [ 11,  12]])
torch.Size([6, 2])
tensor([[  1],
        [  2],
        [  3],
        [  4],
        [  5],
        [  6],
        [  7],
        [  8],
        [  9],
        [ 10],
        [ 11],
        [ 12]])
torch.Size([12, 1])
tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])
torch.Size([12])


In [89]:
print(x)
print(x[0,0])
print(x[0,0].item())
print(type(x[0,0].item()))

tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])
tensor(1)
1
<class 'int'>


## 3. Numpy Bridge

In [90]:
x = torch.tensor([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(x)

x_np = x.numpy()
print(x_np)
print(type(x_np))

x.add_(100)
print(x)

tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
tensor([[ 101,  102,  103,  104],
        [ 105,  106,  107,  108],
        [ 109,  110,  111,  112]])


In [91]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

print("\nInplace update to a changes b")
np.add(a, 1, out=a) # See how changing the np array changed the Torch Tensor automatically

print(a)
print(b)

print("\nApparently using assignment operater assigns a to a new object and tensor remains unchanged")
a = np.add(a, 1)
print(a)
print(b)


print("\nTrying assignment (=) and addition (+) operators. Tensor remains unaffected as expected")
a = np.zeros(5)
b = torch.from_numpy(a)
print(a)
print(b)

a = a + 10
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)

Inplace update to a changes b
[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)

Apparently using assignment operater assigns a to a new object and tensor remains unchanged
[3. 3. 3. 3. 3.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)

Trying assignment (=) and addition (+) operators. Tensor remains unaffected as expected
[0. 0. 0. 0. 0.]
tensor([ 0.,  0.,  0.,  0.,  0.], dtype=torch.float64)
[10. 10. 10. 10. 10.]
tensor([ 0.,  0.,  0.,  0.,  0.], dtype=torch.float64)


## 4. CUDA Tensors

In [92]:
# Creating x on cpu and moving to GPU
x = torch.rand(5,3, device="cpu")
x_cuda = x.to("cuda")
print(x)
print(x_cuda)

# Creating y directly on GPU
# Que: does set_device work to set device to CUDA by default? Ans: NO. See below.

torch.cuda.set_device(0)
y = torch.rand(5,3)
print(y)

y_cuda = torch.rand(5,3, device = "cuda")
print(y_cuda)

# z = x + y_cuda wont work as one is on CPU and other is on CUDA (type )
# error message RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #3 'other'
z_cuda = x_cuda + y_cuda
print(z_cuda)

# moving z_cuda back to cpu
z = z_cuda.to("cpu", torch.double) # ``.to`` can also change dtype together!
print(z)

tensor([[ 0.9944,  0.5702,  0.3273],
        [ 0.0046,  0.8970,  0.2022],
        [ 0.5737,  0.3454,  0.6855],
        [ 0.0337,  0.9575,  0.2402],
        [ 0.0974,  0.8700,  0.6338]])
tensor([[ 0.9944,  0.5702,  0.3273],
        [ 0.0046,  0.8970,  0.2022],
        [ 0.5737,  0.3454,  0.6855],
        [ 0.0337,  0.9575,  0.2402],
        [ 0.0974,  0.8700,  0.6338]], device='cuda:0')
tensor([[ 0.1278,  0.7154,  0.6034],
        [ 0.0985,  0.9652,  0.9980],
        [ 0.3341,  0.6056,  0.2670],
        [ 0.5180,  0.6985,  0.5843],
        [ 0.9313,  0.5222,  0.1637]])
tensor([[ 0.8039,  0.1808,  0.2425],
        [ 0.7167,  0.0076,  0.6950],
        [ 0.4339,  0.2276,  0.5822],
        [ 0.5094,  0.5472,  0.9073],
        [ 0.9800,  0.4349,  0.6650]], device='cuda:0')
tensor([[ 1.7983,  0.7510,  0.5698],
        [ 0.7213,  0.9046,  0.8972],
        [ 1.0076,  0.5730,  1.2677],
        [ 0.5432,  1.5047,  1.1474],
        [ 1.0775,  1.3050,  1.2988]], device='cuda:0')
tensor([[ 1.7983,  

In [93]:
# Original code recommended for this section is as follows: 
#
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 1.9944,  1.5702,  1.3273],
        [ 1.0046,  1.8970,  1.2022],
        [ 1.5737,  1.3454,  1.6855],
        [ 1.0337,  1.9575,  1.2402],
        [ 1.0974,  1.8700,  1.6338]], device='cuda:0')
tensor([[ 1.9944,  1.5702,  1.3273],
        [ 1.0046,  1.8970,  1.2022],
        [ 1.5737,  1.3454,  1.6855],
        [ 1.0337,  1.9575,  1.2402],
        [ 1.0974,  1.8700,  1.6338]], dtype=torch.float64)
