Tutorial URL: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

#  Deep Learning with PyTorch: A 60 Minute Blitz » What is PyTorch?

In [1]:
# preamble
import torch
import numpy as np

## 1. Creating Tensors

In [2]:
x = torch.empty(5,3)
print(x)

x = torch.rand(5,3)
print(x)

x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[ 5.8149e-34,  4.5800e-41,  5.8149e-34],
        [ 4.5800e-41,  0.0000e+00,  0.0000e+00],
        [ 4.6994e-41,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.8214e+36,  4.5799e-41,  1.3593e-43]])
tensor([[ 0.4176,  0.2061,  0.9532],
        [ 0.2701,  0.5799,  0.4466],
        [ 0.6410,  0.0002,  0.1323],
        [ 0.9244,  0.4332,  0.9404],
        [ 0.5329,  0.9482,  0.8269]])
tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [3]:
x = torch.tensor([[5,4,3], [2,1,3]])
print(x)

x = x.new_ones(5,3) # new_* methods take in sizes
print(x)

x = x.new_ones(5,4, dtype=torch.float)
print(x)

x = torch.rand_like(x)
print(x)

x = torch.rand_like(x, dtype=torch.double)
print(x)

tensor([[ 5,  4,  3],
        [ 2,  1,  3]])
tensor([[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]])
tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])
tensor([[ 0.8676,  0.7067,  0.9592,  0.3331],
        [ 0.9716,  0.8013,  0.5994,  0.8046],
        [ 0.6125,  0.1008,  0.8858,  0.4930],
        [ 0.3598,  0.0210,  0.0999,  0.2597],
        [ 0.5440,  0.1891,  0.6431,  0.9837]])
tensor([[ 0.6960,  0.4625,  0.6449,  0.3998],
        [ 0.4955,  0.0599,  0.6374,  0.4669],
        [ 0.3090,  0.9047,  0.4336,  0.3443],
        [ 0.3055,  0.0313,  0.2712,  0.2576],
        [ 0.6524,  0.0862,  0.1550,  0.7709]], dtype=torch.float64)


In [4]:
print(type(x))
print(x.dtype)
print(x.shape)
print(x.size())
print(x.shape[1])

# torch.Size is in fact a tuple, so it supports all tuple operations.

<class 'torch.Tensor'>
torch.float64
torch.Size([5, 4])
torch.Size([5, 4])
4


## 2 Operations

In [5]:
y = torch.rand_like(x)
print(y)

tensor([[ 0.8603,  0.4662,  0.5908,  0.3625],
        [ 0.6159,  0.1536,  0.4698,  0.9551],
        [ 0.3321,  0.1573,  0.7294,  0.6436],
        [ 0.6272,  0.1768,  0.5618,  0.0194],
        [ 0.1556,  0.6656,  0.8483,  0.6424]], dtype=torch.float64)


In [6]:
z = x + y
print(z)

z = torch.add(x,y)
print(z)

z = x.new_zeros(x.size())
print(z)

torch.add(x,y, out=z)
print(z)

y.add_(x)
print(y)

tensor([[ 1.5564,  0.9287,  1.2357,  0.7623],
        [ 1.1114,  0.2135,  1.1073,  1.4221],
        [ 0.6411,  1.0620,  1.1630,  0.9879],
        [ 0.9327,  0.2081,  0.8331,  0.2770],
        [ 0.8080,  0.7517,  1.0033,  1.4133]], dtype=torch.float64)
tensor([[ 1.5564,  0.9287,  1.2357,  0.7623],
        [ 1.1114,  0.2135,  1.1073,  1.4221],
        [ 0.6411,  1.0620,  1.1630,  0.9879],
        [ 0.9327,  0.2081,  0.8331,  0.2770],
        [ 0.8080,  0.7517,  1.0033,  1.4133]], dtype=torch.float64)
tensor([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]], dtype=torch.float64)
tensor([[ 1.5564,  0.9287,  1.2357,  0.7623],
        [ 1.1114,  0.2135,  1.1073,  1.4221],
        [ 0.6411,  1.0620,  1.1630,  0.9879],
        [ 0.9327,  0.2081,  0.8331,  0.2770],
        [ 0.8080,  0.7517,  1.0033,  1.4133]], dtype=torch.float64)
tensor([[ 1.5564,  0.9287,  1.2357,  0.7623],
        [ 1.1114,  0.2135,

In [7]:
# Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.

x = torch.rand(5,3)
print(x)

y = torch.zeros(5,3)
print(y)

x.t_()
print(x)

x.t_()
x.copy_(y)
print(x)

tensor([[ 0.3041,  0.7868,  0.6449],
        [ 0.6496,  0.4086,  0.9860],
        [ 0.0579,  0.9318,  0.3068],
        [ 0.2975,  0.0594,  0.0370],
        [ 0.2659,  0.5434,  0.5602]])
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])
tensor([[ 0.3041,  0.6496,  0.0579,  0.2975,  0.2659],
        [ 0.7868,  0.4086,  0.9318,  0.0594,  0.5434],
        [ 0.6449,  0.9860,  0.3068,  0.0370,  0.5602]])
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])


In [8]:
x = torch.tensor([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(x)
x[1:3, :2] # row 1 and 2, column 0 and 1

tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])


tensor([[  5,   6],
        [  9,  10]])

In [9]:
# Playing with resizing, attempting to convert 
x = torch.tensor([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(x.size())

a = x.view(4,-1) # expected 4,3 
print(a)
print(a.size())

b = x.view(6,2)
print(b)
print(b.size())

c = x.view(12,1)
print(c)
print(c.size())

d = x.view(12)
print(d)
print(d.size())

torch.Size([3, 4])
tensor([[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [ 10,  11,  12]])
torch.Size([4, 3])
tensor([[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10],
        [ 11,  12]])
torch.Size([6, 2])
tensor([[  1],
        [  2],
        [  3],
        [  4],
        [  5],
        [  6],
        [  7],
        [  8],
        [  9],
        [ 10],
        [ 11],
        [ 12]])
torch.Size([12, 1])
tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])
torch.Size([12])


In [10]:
print(x)
print(x[0,0])
print(x[0,0].item())
print(type(x[0,0].item()))

tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])
tensor(1)
1
<class 'int'>


## 3. Numpy Bridge

In [11]:
x = torch.tensor([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(x)

x_np = x.numpy()
print(x_np)
print(type(x_np))

x.add_(100)
print(x)

tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
tensor([[ 101,  102,  103,  104],
        [ 105,  106,  107,  108],
        [ 109,  110,  111,  112]])


In [12]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

print("\nInplace update to a changes b")
np.add(a, 1, out=a) # See how changing the np array changed the Torch Tensor automatically

print(a)
print(b)

print("\nApparently using assignment operater assigns a to a new object and tensor remains unchanged")
a = np.add(a, 1)
print(a)
print(b)


print("\nTrying assignment (=) and addition (+) operators. Tensor remains unaffected as expected")
a = np.zeros(5)
b = torch.from_numpy(a)
print(a)
print(b)

a = a + 10
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)

Inplace update to a changes b
[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)

Apparently using assignment operater assigns a to a new object and tensor remains unchanged
[3. 3. 3. 3. 3.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)

Trying assignment (=) and addition (+) operators. Tensor remains unaffected as expected
[0. 0. 0. 0. 0.]
tensor([ 0.,  0.,  0.,  0.,  0.], dtype=torch.float64)
[10. 10. 10. 10. 10.]
tensor([ 0.,  0.,  0.,  0.,  0.], dtype=torch.float64)


## 4. CUDA Tensors

In [13]:
# Creating x on cpu and moving to GPU
x = torch.rand(5,3, device="cpu")
x_cuda = x.to("cuda")
print(x)
print(x_cuda)

# Creating y directly on GPU
# Que: does set_device work to set device to CUDA by default? Ans: NO. See below.

torch.cuda.set_device(0)
y = torch.rand(5,3)
print(y)

y_cuda = torch.rand(5,3, device = "cuda")
print(y_cuda)

# z = x + y_cuda wont work as one is on CPU and other is on CUDA (type )
# error message RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #3 'other'
z_cuda = x_cuda + y_cuda
print(z_cuda)

# moving z_cuda back to cpu
z = z_cuda.to("cpu", torch.double) # ``.to`` can also change dtype together!
print(z)

tensor([[ 0.0520,  0.5569,  0.7164],
        [ 0.0621,  0.3907,  0.1893],
        [ 0.2425,  0.5678,  0.9082],
        [ 0.1718,  0.0298,  0.5691],
        [ 0.5364,  0.3082,  0.8133]])
tensor([[ 0.0520,  0.5569,  0.7164],
        [ 0.0621,  0.3907,  0.1893],
        [ 0.2425,  0.5678,  0.9082],
        [ 0.1718,  0.0298,  0.5691],
        [ 0.5364,  0.3082,  0.8133]], device='cuda:0')
tensor([[ 0.1925,  0.4294,  0.1796],
        [ 0.3913,  0.9407,  0.6532],
        [ 0.2557,  0.9519,  0.3528],
        [ 0.6666,  0.3100,  0.4265],
        [ 0.2423,  0.4710,  0.2090]])
tensor([[ 0.8610,  0.5125,  0.4972],
        [ 0.9320,  0.1106,  0.8006],
        [ 0.3021,  0.7754,  0.0717],
        [ 0.2022,  0.6917,  0.9921],
        [ 0.1965,  0.5515,  0.7266]], device='cuda:0')
tensor([[ 0.9129,  1.0694,  1.2136],
        [ 0.9940,  0.5013,  0.9899],
        [ 0.5446,  1.3432,  0.9799],
        [ 0.3740,  0.7215,  1.5612],
        [ 0.7329,  0.8598,  1.5399]], device='cuda:0')
tensor([[ 0.9129,  

In [14]:
# Original code recommended for this section is as follows: 
#
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 1.0520,  1.5569,  1.7164],
        [ 1.0621,  1.3907,  1.1893],
        [ 1.2425,  1.5678,  1.9082],
        [ 1.1718,  1.0298,  1.5691],
        [ 1.5364,  1.3082,  1.8133]], device='cuda:0')
tensor([[ 1.0520,  1.5569,  1.7164],
        [ 1.0621,  1.3907,  1.1893],
        [ 1.2425,  1.5678,  1.9082],
        [ 1.1718,  1.0298,  1.5691],
        [ 1.5364,  1.3082,  1.8133]], dtype=torch.float64)
